highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Ricardo Oliveira's Resume
name: Ricardo Martinelli de Oliveira
email: ricardo.martinelli.oliveira@gmail.com
email_full: mailto:ricardo.martinelli.oliveira@gmail.com
website: blog.ricardo.martinelli.nom.br
website_full: https://blog.ricardo.martinelli.nom.br
github: rimolive
linkedin: rmartinelli
meetup: Ansible-Sao-Paulo
orcid: 0000-0002-3716-8734
tel: +55 11999083403
tel_full: tel:+5511999083403
google_maps: 'https://www.google.com/maps/place/R.+Abagiba,+582+-+Vila+da+Sa%C3%BAde,+S%C3%A3o+Paulo+-+SP,+04294-000/@-23.6230432,-46.6117368,15z/data=!4m5!3m4!1s0x94ce5b76ab584975:0x25052efbd7fe53e!8m2!3d-23.6198273!4d-46.6075336'
address:
  street: Rua Abagiba, 582 Apt 53
  postcode: 04294-000
  city: Sao Paulo
  country: Brazil
google_analytics: UA-79558076-2

# needed for travis-ci build
exclude: [vendor]
